[programs.devnet]
raffle = "Hd6vBon1NRw2ksRKEbY7ZB6PqYdKBseMdhSbvA4zpAtw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
